home/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf.urls.defaults import *

urlpatterns = patterns('erp.home.views',
      #(r'^$', 'login'),
      #(r'^login/$', 'login'),
      (r'^forgot_password/$', 'forgot_password'),
      #(r'^login/forgot/$', 'forgot_password'),
      #(r'^login/forgot/(?P<u_name>[a-zA-Z0-9_.-]+)/(?P<new_pass>[\w]+)/?$', 'reset_password'),
      (r'^logout/$', 'logout'),
      #(r'^check/$','check'),
      #(r'^deadlines/$','deadlines'),
      #(r'^registered/$','registered'),
)

search/urls.py
from erp.search.views import *
from django.conf.urls import *
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', search),
    (r'^(?P<search_term>[^/]+)/$', search),
    )

urls.py
from django.conf.urls import *
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
from django.conf import settings
from erp.tasks.views import *
from erp.users.views import *
from erp.home.views import *
from erp.feedback.views import *
from erp.finance.views import *
import haystack
from haystack.views import SearchView
from haystack.forms import ModelSearchForm
from haystack.forms import SearchForm
from haystack.views import search_view_factory
from django.conf.urls import *
from tasks.views import *
from django.conf.urls.defaults import *

#haystack.autodiscover()
dajaxice_autodiscover()
#admin.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)
 
urlpatterns = patterns('',
    #(r'^134c036048b637ac75edcd4352212e55/$', 'erp.home.dbscript.write_into_db'), #used to load coord/core details into db.
    (r'^dajaxice/', include('dajaxice.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    (r'^forgot_password/$','erp.home.views.forgot_password'),
    #(r'^search/', include('haystack.urls')),
    url(r'^$', 'erp.home.views.login', name='home'),
    (r'^search/', include('erp.search.urls')),
    #(r'^erp/$', include('erp.home.urls')),
    (r'^erp/home/',include('erp.home.urls')),
    #(r'^erp/users/', include('erp.users.urls')),
    #(r'^erp/dashboard/',include('erp.dashboard.urls')),	
    # Make the above 2 URLConfs look like these 2 below
	(r'^erp/(?P<owner_name>\w+)/feedback/', include('erp.feedback.urls')),
	(r'^erp/feedback/', include('erp.feedback.urls')),
	(r'^erp/finance_portal/',include('erp.finance.urls')),
	(r'^erp/facilities/',include('erp.facilities.urls')),
	(r'^erp/prizes/(?P<owner_name>\w+)/', include('erp.prizes.urls')),
    (r'^erp/(?P<owner_name>\w+)/users/', include('erp.users.urls')),
    (r'^erp/(?P<owner_name>\w+)/dashboard/',include('erp.dashboard.urls')),	
    (r'^erp/(?P<owner_name>\w+)/', include('erp.tasks.urls')),
    (r'^erp/forgot_password/$', 'erp.home.views.forgot_password'),
    (r'^loaddata/$', 'erp.dashboard.views.load_data'), #used to load test data into db.
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    
    #(r'^now/sign.html$', sign_in, ),
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url(r'^task/remainder/email/$', 'erp.tasks.views.remainder', name='remainder'),
)

search/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from erp.department.models import Department
from erp.misc.helper import is_core, is_coord, get_page_owner

# Create your models here.
#The choices may be cup level but if any thing better pls do change.
STAT_CHOICES= (
	('O','Open'),
	('C','Completed'),
	('L','Overdue'),
	('N','Almost'),
)

DEFAULT_STATUS = 'O'
    
class AbstractBaseTask(models.Model):
    """
    Abstract Base Class for Task, SubTask.

    TODO:
    * File upload
    * Draft saving
    * QMS Manager for the Task
    """
    subject         = models.CharField(max_length=100 , null=True)
    description     = models.TextField(null=True , blank=True)
    creator         = models.ForeignKey(User, related_name = '%(app_label)s_%(class)s_creator')
    creation_date   = models.DateTimeField (auto_now = True, editable = False)
    deadline        = models.DateField(null=True , blank=True)
    status          = models.CharField(max_length=1,choices=STAT_CHOICES,default = DEFAULT_STATUS)	
    completion_date = models.DateField(null=True , blank=True)
    feedback        = models.TextField(null=True, blank=True)
    class Meta:
        abstract = True
        
class Task(AbstractBaseTask):

    """
    Task Model

    Note : The department where the Task originated is understood from
    the Creator's department. As of now, only Cores can create Tasks.

    A Task mainly consists of SubTasks which are created and assigned by the respective Cores of each department.
    """

    def is_owner (self, user):
        """
        user is the owner of the current Task if
        - user is a Core in the Task's department
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.creator.get_profile ().department
        return user.get_profile ().department == self.creator.get_profile ().department and (not is_coord (user))

    def __str__(self):
        return self.subject

    class Admin:
        pass

class SubTask(AbstractBaseTask):
    """
    SubTask Model

    As of now, SubTasks can be created mainly in two places :

    * When a Core breaks Tasks down into SubTasks and assigns some of
      them to Coords in his own department and/or delegates a SubTask
      to another Department (whose core has to then assign that
      SubTask to that department's coords, possibly creating more
      SubTasks as required)

    * When a Coord creates goals with deadlines for himself (these are
      called SubTasks but will actually be shown in his Timeline and
      handled differently from SubTasks that have been assigned to him
      by Cores)
    """
    coords = models.ManyToManyField (User, blank = True)
    department = models.ForeignKey (Department)
    task = models.ForeignKey (Task)

    def is_owner (self, user):
        """
        user is the owner of the current SubTask if
        - user is a Core in the department which created the Task
          which SubTask is related to
        - user is a Core in the department to which SubTask is assigned
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.task.creator.get_profile ().department
        print 'SubTask Dept : ', self.department
        user_dept = user.get_profile().department
        return (not is_coord (user)) and (
            (user_dept == self.task.creator.get_profile ().department) or
            (user_dept == self.department))

    def is_assignee (self, user):
        """
        Return True if user is a Coord who has been assigned this subtask.
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Coord : ', is_coord (user)
        user_dept = user.get_profile().department
        return is_coord (user) and (self.coords.filter (id = user.id).exists ())

    def __str__(self):
        return self.subject

    class Admin:
        pass

class AbstractComment (models.Model):
    """
    Abstract Base Class to store a comment.

    Timestamp helps to order comments. It is generated automatically.
    Author can be used to select particular comments based on the author.
    """
    author = models.ForeignKey (User, related_name = '%(app_label)s_%(class)s_author')
    comment_string = models.TextField ()
    time_stamp = models.DateTimeField (auto_now = True, editable = False)

    class Meta:
        abstract = True
        ordering = ['time_stamp']

class TaskComment(AbstractComment):
    """
    Comment written for a Task.
    """
    task = models.ForeignKey (Task)

    def __str__(self):
        return '%s %s' %(self.task.subject, self.id)
    class Admin:
        pass
        
        
class SubTaskComment(AbstractComment):
    """
    Comment written for a SubTask
    """
    subtask = models.ForeignKey (SubTask)

    def __str__(self):
        return '%s %s' %(self.subtask.subject, self.id)
    class Admin:
        pass
        
class Label(models.Model):
    labelname = models.ForeignKey(Task, related_name="task_label")
    
class Update (AbstractComment):
    """
    Used by Coord to send updates to a Core
    """
    class Admin:
        pass

home/forms.py
from django.db import models
from django.forms import ModelForm
from models import *
from django import forms
from django.contrib.auth.forms import PasswordResetForm

from django.contrib.auth.hashers import UNUSABLE_PASSWORD, is_password_usable, get_hasher

class UserLoginForm(forms.Form):
    username=forms.CharField(help_text='Your username as registered with the ERP')
    password=forms.CharField(widget=forms.PasswordInput, help_text='Your password. If you do not remember this, please use the link below')
    
class forgot_password_form(ModelForm):
	
	class Meta:
		model=forgot_password
		exclude=('date',)
		
class ModifiedPasswordResetForm(PasswordResetForm):
    def clean_email(self):
        """
        Validates that an active user exists with the given email address.
        """
        email = self.cleaned_data["email"]
        query = User.objects.filter(email__iexact=email,
                                               is_active=True)
        try:
            user = User.objects.filter(username=sortlist([x.username for x in query])[-1])
            self.users_cache = user
        except:
            self.users_cache = []
        if not len(self.users_cache):
            raise forms.ValidationError(self.error_messages['unknown'])
        if any((user.password == UNUSABLE_PASSWORD)
               for user in self.users_cache):
            raise forms.ValidationError(self.error_messages['unusable'])
        return email
        
def bylength(word1,word2):
    return len(word2)-len(word1)

def sortlist(a):
    a.sort(cmp=bylength)
    return a	

tasks/forms.py
from django.db import models
from django.forms import ModelForm
from models import *
from django import forms
from chosen import forms as chosenforms
from erp.department.models import *
from erp.users.models import *
from django.contrib.auth.models import User
#from chosen import widgets as chosenwidgets

class TaskCommentForm (ModelForm):
	comment_string=forms.CharField(label='Comments',widget=forms.Textarea)
	class Meta:
		model=TaskComment
		exclude=('author','task')	

class SubTaskCommentForm (ModelForm):
    class Meta:
        model = SubTaskComment
        exclude = ('author', 'subtask')                

class UpdateForm (ModelForm):
    class Meta:
        model = Update
        exclude = ('author')

class TaskForm (ModelForm):
    class Meta:
        model = Task
        exclude = ('creator', 'completion_date')
        widgets = {'status': chosenforms.widgets.ChosenSelect()}

class SubTaskForm (ModelForm):
    class Meta:
        model = SubTask
        exclude = ['creator', 'task', 'completion_date']
        widgets = {'department':chosenforms.widgets.ChosenSelect(),'coords': chosenforms.widgets.ChosenSelectMultiple(),'status': chosenforms.widgets.ChosenSelect()}

#to restrict coords for a core. Currently all coords display for a core. Code results in cups because of a cup in
#      # Let the Core save the SubTask
#            curr_subtask_form = SubTaskForm (request.POST, instance = curr_subtask)  line 336 in tasks/views.py  
#
#

#   The Curry issue has been fixed. However, when trying to edit a form, it does not change the form because it isn't valid 
#   for some reason. Line 469  if curr_subtask_form.is_valid (): returns FALSE. So the subtask just reloads itself without any changes.
#

    def __init__(self, editor=None, *args, **kwargs):
        if isinstance(editor,User):
            # The reason it is isinstance is because when i'm editing a subtask in particular, 
            # junk values are getting passed to editor in POST method.
            # To check, make it
        # if editor:
            # The code will fail but editor will be a random dictionary of variables.
            super(SubTaskForm, self).__init__(*args, **kwargs)
            print "THIS IS", editor
            self.fields['coords'].queryset = User.objects.filter(userprofile__department=editor.get_profile().department)
            self.fields['coords'].label_from_instance = lambda obj: "%s - %s" % (obj.get_profile ().name, obj.get_profile ().nickname)
            self.fields['coords'].help_text = ''
        else:
            super(SubTaskForm, self).__init__(editor,*args, **kwargs)   

        
#hack if these fields need to be formatted        
#    def __init__(self, *args, **kwargs):
#        super(SubTaskForm, self).__init__(*args, **kwargs)
#        self.fields['subject'].widget.attrs['rows'] = '500'
#        self.fields['subject'].widget.attrs['cols'] = '500'
        

home/views.py
from django.shortcuts import render_to_response, redirect
#from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import auth
from django.contrib.auth.views import password_reset
from django.template.loader import get_template
from django.template.context import Context, RequestContext
from django.utils.translation import ugettext as _
from django.core.mail import send_mail,EmailMessage,get_connection
from django.core.mail import send_mail,EmailMessage
from django.contrib.sessions.models import Session
from erp.home.forms import *
from erp.misc.helper import *
import models,forms
from erp.misc.util import *
# Take care of session variable
from erp.home import models
from erp.users.models import *

def home(request):
    redirected = session_get (request,"from_url")
    access_denied = (request, "access_denied")
    logged_in = session_get (request, "logged_in")
    already_logged = session_get (request, "already_logged")
    return render_to_response('home/home.html', locals(), context_instance= global_context(request))

# <> So Users once logged in, can't access the login page
def login(request):
    if request.user.is_authenticated():
        return redirect ('erp.tasks.views.display_portal', owner_name = request.user.username)
    redirected = request.session.get ("from_url", False)
    just_registered = session_get(request, "just_registered")
    form = forms.UserLoginForm ()
    print "just before if"
    if request.method == 'POST':
        print "in the login , it is post"
        data = request.POST.copy()
    
        form =forms. UserLoginForm (data)
        if form.is_valid():
                user = auth.authenticate(username=form.cleaned_data['username'],
                                         password=form.cleaned_data["password"])
                if user is not None and user.is_active == True:
                    auth.login (request, user)
        
        
                    # WHERE THE HELL IS THIS USED?
                    # url = session_get(request, "from_url")
                    # # Handle redirection
                    # if not url:
                    #     url = "%s/home/"%settings.SITE_URL
        
        
                    request.session['logged_in'] = True
        
                    try:
                        response.set_cookie('logged_out', 0)
                    except:
                        pass

                    if redirected:
                        return redirect (redirected)
                    else:
                        return redirect ('erp.tasks.views.display_portal',
                                         owner_name = user.username)
                else:
                    invalid_login_message="Incorrect username or password. Please try again."
                    request.session['invalid_login'] = True
                    print "the user has not logged in -invalid "
                    print request.path
                    return render_to_response('home/login.html', locals(), context_instance= global_context(request))
                    #return HttpResponseRedirect (request.path)
                    invalid_login =session_get(request, "invalid_login")
                    form = forms.UserLoginForm ()
        else:
            pass
    return render_to_response('home/login.html', locals(), context_instance= global_context(request))
    
def logout (request):
    print 'HERE'
    if request.user.is_authenticated():
        auth.logout (request)
        response= redirect ('erp.home.views.login')

        try:
          #  response.set_cookie('unb_User',"")
            response.set_cookie('logged_out', 1)
        except:
            pass
        return response
    return render_to_response('home/login.html', locals(), context_instance= global_context(request))

def forgot_password(request):
    return password_reset(request,password_reset_form=ModifiedPasswordResetForm)
    

templates/base_portal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Shaastra | ERP - Alpha Release</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ MEDIA_URL }}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
      padding-top: 60px;
      padding-bottom: 40px;
      background: white;
      }

      .span4 {
      padding-top: 10px;
      padding-left: 0px;
      padding-bottom: 50px;
      }
      
      #logo {
      color: #ffffff;
      }	
      #id_description {
      width:350px; 
      height:80px;
      
      }
      #id_subject {
      width:350px; 
      
      }
      #id_deadline {
      width:350px;
      }
      #id_status {
      width:350px;
      }
      #id_comment_string {
      width:350px;
      height:40px;
      }
      
      
    </style>
    <link href="{{ MEDIA_URL }}css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/chosen.css" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    <link rel="shortcut icon" href="{{ MEDIA_URL }}images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ MEDIA_URL }}images/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ MEDIA_URL }}images/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ MEDIA_URL }}images/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ MEDIA_URL }}images/apple-touch-icon-57-precomposed.png">
    
    <script>
      $('#myTab a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
      })
      
      function searchterm()
      {
      return document.getElementById('searchbar').value
      
      }
    </script>
    {% block extrahead %}
    {% endblock %}
    {% block extrastyle %}
    {% endblock %}
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35704180-1']);
      _gaq.push(['_trackPageview']);

     (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

    </script>
  </head>

  <body>
    <div class="modal hide" id="changepassword">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">×</button>
	<h3>Change Password</h3>
      </div>
      <div class="modal-body">
	<p>Enter the details to change your password</p>
	<form class = "form-horizontal" action="{% url users.views.change_password owner_name=user %}" method="POST">
	  {% csrf_token %}
	  
	  <fieldset>
	    <div class="control-group">
	      <label class="control-label" for="old_pass">Enter your current password: </label>
	      <div class="controls">
		<input type="password" class="input-xlarge" id="old_pass" name="old_pass">
	      </div>
	    </div>
	    <div class="control-group">
	      <label class="control-label" for="new_pass1">Enter your new password: </label>
	      <div class="controls">
		<input type="password" class="input-xlarge" id="new_pass1" name="new_pass1">
	      </div>
	    </div>
	    <div class="control-group">
	      <label class="control-label" for="new_pass2">Re-enter your new password: </label>
	      <div class="controls">
		<input type="password" class="input-xlarge" id="new_pass2" name="new_pass2">
	      </div>
	    </div>
	  </fieldset>
	  
	  
	  
      </div>
      <div class="modal-footer">
	<input type="submit" class="btn btn-primary" value="Change Password">
      </form>
      </div>
    </div>
    
    <div class="modal hide" id="contact">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">×</button>
	<h3>Contact Us:</h3>
      </div>
      <div class="modal-body">
      <h4><u>Web-Operations Cores:</u></h4><br>
	<p><strong>Chetan Bademi:</strong> +919962247480</p>
	<p><strong>Akshay Rangasai:</strong> +919940070478</p><br>
	  <u><h4>Web-Operations QMS</h4></u><br>
	<p><strong>Mohammed Rhazy:</strong> +919445420781</p><br><br>
    <!-- Or you can just contact Swapnil or Sriram :P -->
	<p><h5>Email us for bugs, queries or if you're feeling lonely:</h5> shaastra@shaastra.org<br>

	  
	  </div>
      <div class="modal-footer">
      <h6> You can try Deep Thought too, but I don't think 42 is of much help. </h6>
      
      </div>
    </div>
    
    
    
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
          <ul class="nav">
            <li>
              <a class="brand" href="{% url tasks.views.display_portal owner_name=user %}" id="logo"><i class="icon-globe icon-white" style="margin-top:5px;"></i> ERP</a>
            </li>
          </ul>

          <ul class=" nav pull-right">
            
          </ul>
          
          
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i  class="icon-th-large"></i> Actions
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url users.views.handle_profile owner_name=user %}"><i class="icon-tag"></i> Edit Profile</a></li>
              <li><a data-toggle="modal" href="#changepassword"><i class="icon-lock"></i> Change Password</a></li>
              <li>
                <a href="{% url home.views.logout %}"><i class="icon-off"></i> Sign Out</a>
              </li>
            </ul>
	  </div>


          
          <div class="nav-collapse">
            <ul class="nav">
              <li id="nav_home">
                <a href="{% url tasks.views.display_portal owner_name=user %}"><i class="icon-home icon-white"></i> Home</a>
              </li>
              <li id="nav_profile">
                <a href="{% url users.views.view_profile owner_name=user%}"><i class="icon-user icon-white"></i> Profile</a>
              </li>
              <li id="nav_contact">
                <a data-toggle="modal" href="#contact"><i class="icon-wrench icon-white"></i> Contact</a>
              </li>

            </ul>
            <ul class="nav">
              <li>

                <div class="input-append">
                  <form class="navbar-search" id="search" action="/search/" method="POST">
                    {%csrf_token%}
                    <div class="input-append">
                      <input type="text" style="border-radius:13px 13px 13px 13px;" class="input-xlarge search-query" placeholder="Search" name="searchbar">
                      <a href="#" id="search-icon"><i class="icon-search" style="margin-top:2px; z-index:3;position:absolute;right:10px;top:5px;"></i></a> 
                    </div>
                  </form>
                </div>
              </li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">


            <!-- CHAMPI BASAK! CHAMPI BASAK! CHAMPI BASAK! CHAMPI BASAK! -->
            
            <div class="page-header white">
                <h2>Welcome, {{user.get_profile.name}}!
                {% block multiple %}
                <div class="pull-right">
                {% if is_core %}
                {% if supercore %}
                <a href="{% url tasks.views.multiple_logout owner_name=user %}">
                <button class="btn btn-danger large">

                <strong>Change Department</strong></button>
            </a>
            {% endif %}
            {% endif %}
            {% if is_coord %}
            {% if multiple_coord %}
            <a href="{% url tasks.views.multiple_logout owner_name=user %}">
              <button class="btn btn-danger large">
                <strong>Change Department</strong></button>
            </a>
            {% endif %}
            {% endif %}                
            <div>
              {% endblock %}
        </h2>
        </div>
        <br/>
        <div class="row">
          
          <div class="tabbable span12">
            
            {% if not is_multiple_user %}
            <ul class="nav nav-pills nav-stacked span2" id="myTab">
              {% include "left-sidebar.html" %}
              <hr>
              {% include "right-sidebar.html" %}
            </ul>
            {% endif %}
            <div class="tab-content span9" style="overflow:visible;">
              {% block body %}
              {% endblock %}
              {% block tabs %}
              {% endblock %}
              {% block form_stuff %}
              {% endblock %}
              {% block display_stuff %}
              {% endblock %}
            </div><!-- /.tab-content -->
          </div><!-- /.tabbable -->
        </div><!-- /.row -->

        </div>
        
        
        
        <!-- ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        
        {% block javascript %}
        <script src="{{ MEDIA_URL }}js/jquery.js"></script>
        <script src="{{ MEDIA_URL }}js/bootstrap.min.js"></script>
        <script src="{{ MEDIA_URL }}js/bootstrap-modal.js"></script>
        <script src="{{ MEDIA_URL }}js/bootstrap-dropdown.js"></script>
        <script src="{{ MEDIA_URL }}js/bootstrap.min.js"></script>
        <script src="{{ MEDIA_URL }}js/jquery.dajax.core.js"></script>
        <script src="{{ MEDIA_URL }}js/chosen.jquery.js"></script>
        <script type="text/javascript">
          function showMembers() {
          var d = document.getElementById("department_members_icon");
          if(d.className=="icon-plus-sign") {
          d.className = "icon-minus-sign";
          }
          else {
          d.className = "icon-plus-sign";
          }
          }
        </script>
        <script type="text/javascript">
          function showComments(tab, task_id) {
          var d = document.getElementById(tab + "_comments_" + task_id + "_icon");
          var e = document.getElementById(tab + "_comments_" + task_id + "_text");
          if(d.className=="icon-plus-sign") {
          d.className = "icon-minus-sign";
          e.innerHTML="Hide";
          }
          else {
          d.className = "icon-plus-sign";
          e.innerHTML="Show";
          }
          }
          function showSubtasks(tab, task_id) {
          var d = document.getElementById(tab + "_subtask_" + task_id + "_icon");
          var e = document.getElementById(tab + "_subtask_" + task_id + "_text");
          if(d.className=="icon-plus-sign") {
          d.className = "icon-minus-sign";
          e.innerHTML="Hide";
          }
          else {
          d.className = "icon-plus-sign";
          e.innerHTML="Show";
          }
          }
        </script>

        <script type="text/javascript">
          $('#id_status').chosen();
          $('#id_coords').chosen();
        </script>
        <script type="text/javascript">        
          $('#search-icon').click(function() {
          $('#search').submit();
          });
        </script>
        <script type="text/javascript">
          $("#task_delete").click(function() {
          var notif = document.getElementById("alertdiv");
          notif.className = "alert alert-block alert-error fade in";
          alertdiv.innerHTML = '<button type="button" class="close" data-dismiss="alert">&times;</button><h4 class="alert-heading">Are you sure you want to delete the selected tasks?</h4><br><input class="btn btn-danger" type="submit" name="delete" value="Yes"><a class="btn" data-dismiss="alert">No</a>';
          });
        </script>
        {% endblock %}
  </body>

</html>

templates/gen.html
Done