urls.py
from django.conf.urls import *
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
from django.conf import settings
from erp.tasks.views import *
from erp.users.views import *
from erp.home.views import *
from erp.feedback.views import *
from erp.finance.views import *
import haystack
from haystack.views import SearchView
from haystack.forms import ModelSearchForm
from haystack.forms import SearchForm
from haystack.views import search_view_factory
from django.conf.urls import *
from tasks.views import *
from django.conf.urls.defaults import *

#haystack.autodiscover()
dajaxice_autodiscover()
#admin.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)
 
urlpatterns = patterns('',
    #(r'^134c036048b637ac75edcd4352212e55/$', 'erp.home.dbscript.write_into_db'), #used to load coord/core details into db.
    (r'^dajaxice/', include('dajaxice.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    (r'^forgot_password/$','erp.home.views.forgot_password'),
    #(r'^search/', include('haystack.urls')),
    url(r'^$', 'erp.home.views.login', name='home'),
    (r'^search/', include('erp.search.urls')),
    #(r'^erp/$', include('erp.home.urls')),
    (r'^erp/home/',include('erp.home.urls')),
    #(r'^erp/users/', include('erp.users.urls')),
    #(r'^erp/dashboard/',include('erp.dashboard.urls')),	
    # Make the above 2 URLConfs look like these 2 below
	(r'^erp/(?P<owner_name>\w+)/feedback/', include('erp.feedback.urls')),
	(r'^erp/feedback/', include('erp.feedback.urls')),
	(r'^erp/finance_portal/',include('erp.finance.urls')),
	(r'^erp/facilities/',include('erp.facilities.urls')),
	(r'^erp/prizes/(?P<owner_name>\w+)/', include('erp.prizes.urls')),
    (r'^erp/(?P<owner_name>\w+)/users/', include('erp.users.urls')),
    (r'^erp/(?P<owner_name>\w+)/dashboard/',include('erp.dashboard.urls')),	
    (r'^erp/(?P<owner_name>\w+)/', include('erp.tasks.urls')),
    (r'^erp/forgot_password/$', 'erp.home.views.forgot_password'),
    (r'^loaddata/$', 'erp.dashboard.views.load_data'), #used to load test data into db.
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    
    #(r'^now/sign.html$', sign_in, ),
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url(r'^task/remainder/email/$', 'erp.tasks.views.remainder', name='remainder'),
)

users/urls.py
from django.conf.urls import *
from django.views.generic.simple import *
from django.conf.urls.defaults import *

urlpatterns = patterns('erp.users.views',
      (r'^$', 'handle_profile'),
      (r'^register/?(?P<dept_name>\w+)?/$', 'register_user'),
      # (r'^register_invite/?(\w+)?/?(\w+)?/?(\w+)?/$', 'register_invite'),
      (r'^invite/$', 'invite'),
      (r'^profile/$', 'view_profile'),
      (r'^edit_profile/$', 'handle_profile'),
      (r'^change_password/$','change_password'),
      (r'^search/', include('haystack.urls')),

)

urlpatterns +=patterns('',
      (r'^change_profile_pic/$', 'erp.dashboard.views.change_profile_pic'),
)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from erp.department.models import *
from django.conf import settings
# Create your models here.

GENDER_CHOICES = (
    ('M','Male'),
    ('F','Female'),
)

HOSTEL_CHOICES  =(
        ("Ganga", "Ganga"),
        ("Mandak", "Mandak"),
        ("Jamuna", "Jamuna"),
        ("Alak", "Alak"),
        ("Saraswathi", "Saraswathi"),
        ("Narmada", "Narmada"),
        ("Godav", "Godav"),
        ("Pampa", "Pampa"),
        ("Tambi", "Tambi"),
        ("Sindhu", "Sindhu"),
        ("Mahanadi", "Mahanadi"),
        ("Sharavati", "Sharavati"),
        ("Krishna", "Krishna"),
        ("Cauvery", "Cauvery"),
        ("Tapti", "Tapti"),
        ("Brahmaputra", "Brahmaputra"),
        ("Sarayu", "Sarayu"),
        )

class userprofile(models.Model):
    """
    User's profile which contains all personal data.
    """
    user = models.ForeignKey(User, unique=True)
    nickname = models.CharField(max_length=30, blank=True)
    name = models.CharField(max_length=30, blank=True)
    department = models.ForeignKey(Department, blank=True, null=True)
    chennai_number = models.CharField(max_length=15, blank=True)
    summer_number = models.CharField(max_length=15, blank=True)
    summer_stay = models.CharField(max_length=30, blank=True)
    hostel = models.CharField(max_length=15, choices = HOSTEL_CHOICES, blank=True)
    room_no = models.IntegerField(default=0, blank=True)

    class Meta:
        pass

    def __str__(self):
        return '%s %s' %(self.user.username, self.nickname)

    class Admin:
        pass

class Materials(models.Model):
    # name of the  person who asked or gave
    user = models.ForeignKey(User, unique=True, related_name="item_borrower")
    # the material which has been asked for
    item = models.CharField(max_length=50)
    # no. of items borrowed
    item_no = models.IntegerField(default=1)
    # time of borrow
    borrowed_time = models.DateTimeField(null=True ,blank=True)
    # time of return
    return_time = models.DateTimeField(null=True ,blank=True)
    # if the person got/given the item this will be true
    item_got = models.BooleanField(default=False)
    # if the person returns/takes the item this will be true
    item_returned = models.BooleanField(default=False)
    # name of the person/hostel/deptartment borrowed/lent from
    user_2 = models.ForeignKey(User , unique=True, related_name="item_lender")

    def __str__(self):
        return self.item

    class Admin:
        pass

class invitation(models.Model):
    core = models.ForeignKey(User , related_name="the core who has invited the user")
    invitee = models.CharField(max_length=50)#name of the coord
    roll_no = models.CharField(max_length=8)
    email_id = models.EmailField()
    time = models.DateField()

    class Admin:
	pass

class userphoto(models.Model):
    name=models.ForeignKey(User)
    photo_path=models.FileField(upload_to=settings.MEDIA_ROOT)

    def __str__(self):
	return str(self.photo_path)
    class Admin:
	pass

users/views.py
# Create your views here.
from django.shortcuts import render_to_response, redirect
# from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import auth
from django.contrib.auth.models import User
from django.template.loader import get_template
from django.template.context import Context, RequestContext
from forms import * 
from django import forms
from erp.users.models import *
from erp.misc.util import *
from erp.misc.helper import *
from erp.department.models import *
from erp.dashboard.forms import *
from django.forms.models import modelformset_factory			
from django.contrib.auth.models import Group,Permission
import sha,random,datetime
from erp.users.forms import *
from django.core.mail import send_mail,EmailMessage
from django.conf import settings
import os
import re


def register_user(request, dept_name="Events", owner_name = None):
    """
    for test phase the default dept is Events
    """
    print "this is the deptname user belongs to ",dept_name
    department=Department.objects.filter(Dept_Name = dept_name)
    user_form = AddUserForm ()
    profile_form = userprofileForm ()
    if request.method=='POST':
        user_form = AddUserForm (request.POST)

        if user_form.is_valid():
            # Create the User
            new_user = User.objects.create_user(
                username = user_form.cleaned_data['username'],
                email = user_form.cleaned_data['email'],
                password = user_form.cleaned_data['password'],
                )    
            # Save his profile - mainly his dept name
            #here if must be changed to try
	    if True:
	        department=Department.objects.get(Dept_Name = dept_name)
		profile=userprofile.objects.create(user=new_user ,department=department)
                profile.save()
                #creating a folder for the user
		print "user profile saved"
		
                print "trying to craete a folder for the user and assigning a default profile pic"
                file_name="PROFILE_PIC_OF_THE_USER"
                savepath ,file_path=create_dir(file_name  , user_form.cleaned_data['username'])
                image_object=userphoto(name=new_user ,photo_path="http://localhost/django-media/upload_files/ee10b000/PROFILE_PIC_OF_THE_USER")
                image_object.save()
                print "created folder and given default user_profil_pic"
	    else:
		print "userprofile not saved ,check out"
            # Make the user a Coord
            new_user.groups.add (Group.objects.get (name = 'Coords'))
            new_user.is_active=True #took from userportal
            new_user.save()
            registered_successfully = True
            request.session['just_registered'] = True
            return redirect ('erp.home.views.login')
	else:
	    print "the user form is not valid the errors are :"
	    print user_form.errors
            return render_to_response('users/register.html' , locals() ,context_instance = global_context(request))
    else:
        return render_to_response('users/register.html' , locals() ,context_instance = global_context(request))

        
      


# WTH is this?

# def register_invite(request,dept_name="none" ,username="none" ,rollno="ee0b000"):
#     print "deptname :" ,dept_name
#     user_form = AddUserForm (initial={'username':rollno},)
#     return render_to_response('users/register.html' , locals() ,context_instance = global_context(request))


@needs_authentication
def invite(request ,owner_name):
    CsvForm=UploadFileForm(initial={'title':"Enter the name" , 'short_description':"you may write anything here"})
    message=[]
    message+=["start"]
    User=request.user
    user_dept = str(User.userprofile_set.all()[0].department)
    print user_dept
    success_message="" 
    if request.method=='POST':
        form=InviteForm(request.POST)
        if form.is_valid():
            message+=["form valid "]
            name=form.cleaned_data['invitee']
            emailid=form.cleaned_data['email_id']
            roll_no=form.cleaned_data['roll_no']
            

            # print settings.SITE_URL+"/users/register_invite/"+user_dept+"/"+name+"/"+roll_no+"/"
            invite_details=invitation(
            core=request.user,
            invitee=name,
            email_id=emailid,
            time=datetime.datetime.now(),
            )#this stores the information of invitation
            try:
                #here the essential mail details are assigned
                hyperlink=settings.SITE_URL+"/users/register_invite/"+user_dept+"/"+name+"/"+roll_no+"/"
                mail_header="Invitaiton from the core to join ERP"
                mail=[emailid,]
		print mail
                #sending mail here
                print "came till the function part"
                success_message=mail_coord(hyperlink ,mail_header ,name ,"users/emailcoords.html" ,mail ) 
               
            except:
                message+=["mail could not be sent "]
                success_message=["mail could not be sent may be wrong details"]
                print "mail not sent."
                pass

		

    else:
        message+=["form not valid"]
    form=InviteForm()
    return render_to_response('dashboard/invite.html',locals(),context_instance = global_context(request))



"""
this part yet to be done
"""
@needs_authentication
def invite_inbulk(request ,self):
    CsvForm=UploadFileForm(initial={'title':"Enter the title" , 'short_description':"you may write anything here"})
    form=InviteForm()
    if request.method=='POST':
        pass



            
@profile_authentication
def view_profile(request, owner_name=None):
    page_owner = get_page_owner (request, owner_name)
    try:
        image=userphoto.objects.get(name=page_owner)
        photo_path =image.photo_path
    except:
        if is_multiple_user(request.user):
            multiple = userprofile.objects.all()
            for each in multiple:
                if (each.user.username.startswith(request.user.username.lower()) and each.user.username!=request.user.username):
                    image=userphoto.objects.get(name = each.user)
                    photo_path =image.photo_path
                    break

    profile = userprofile.objects.get(user=page_owner)
    group = str(page_owner.groups.all()[0])[:-1] #drop 's' from group name. Ex: 'Core' from 'Cores'
    print profile.nickname
    print profile.name

    #Get Department Members' image thumbnails
    department = request.user.get_profile ().department      
    dept_cores_list = User.objects.filter (
        groups__name = 'Cores',
        userprofile__department = department)
    dept_supercoords_list = User.objects.filter (
        groups__name = 'Supercoords',
        userprofile__department = department)
    dept_coords_list = User.objects.filter (
        groups__name = 'Coords',
        userprofile__department = department)

    curr_user=request.user
    curr_userprofile=userprofile.objects.get(user=request.user)    
    if is_core(curr_user):
		if str(curr_userprofile.department) == 'QMS':
			qms_core= True

    if is_supercoord(curr_user):
        if str(curr_userprofile.department) == 'QMS':
            qms_supercoord= True
            
    if is_coord(curr_user):
		if str(curr_userprofile.department) == 'QMS':
			qms_coord= True

    return render_to_response('users/view_profile.html',locals(),context_instance = global_context(request))
    	
@needs_authentication_multiple_user
def handle_profile (request, owner_name):
    print request.user.id , "is the id of the user"

    user = request.user
    profile = userprofile.objects.get(user=request.user)
    if request.method=='POST':
        try:
            supercores = request.user.get_profile().department.owner.all()     #check if the department has a supercore, else department.owner will be NULL, and go to except.
            supercore=supercores[0]
            for x in supercores:
                if request.user.username.startswith(x.username.lower()):
                    supercore = x
                    break
                    
            if request.user.username.startswith(supercore.username.lower()):                  #checking if the supercore is using one of his core accounts.
                profile = userprofile.objects.get(user = supercore)
                profile_form = userprofileForm (request.POST, instance = profile)
                if profile_form.is_valid():
                    profile_form.save ()
                departments = supercore.department_set.all()
                for dept in departments:
                    allUserProfiles = userprofile.objects.filter(department = dept)
                    for each in allUserProfiles:
                        if each.user.username.startswith(supercore.username.lower()):
                            profile_form = userprofileForm (request.POST, instance = each)
                            if profile_form.is_valid():
                                profile_form.save()
            else:                                                            
                department = request.user.get_profile().department
                if request.user.username.endswith(re.sub('[^a-zA-Z0-9]', '', department.Dept_Name).lower()):                #a multiple coord-associated acc.
                    allUserProfiles = userprofile.objects.all()
                    multiple_coord=request.user.username.split('_')[0]
                    for each in allUserProfiles:
                        if each.user.username.startswith(multiple_coord.lower()):
                            profile_form = userprofileForm (request.POST, instance = each)
                            if profile_form.is_valid():
                                profile_form.save()

templates/users/change_password.html
{% include "base_portal.html" %}
{% block tabs %}
{% if changed %}
<div class="alert alert-success">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <center>
    <strong> You have successfully changed your password. </strong>
  </center>
</div>
{% endif %}
{% if failed %}
<div class="alert alert-error">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <center>
    <strong> Your passwords don't match! </strong>
  </center>
</div>
{% endif %}
{% if invalid %}
<div class="alert alert-error">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <center>
    <strong> The password you entered is wrong! </strong>
  </center>
</div>
</div>
{% endif %}

{% endblock %}

templates/users/change_profile_pic.html
{% extends "base_portal.html" %}
{% block body %}


<form enctype="multipart/form-data" action="{% url dashboard.views.change_profile_pic  owner_name=user%}" method ="POST">
  {% csrf_token %}

{% for field in pic_form %}
{{field.label_tag}}

    {{field}}
    
    

{% endfor %}</br>
<input type="submit" value ="Change ">
</form>

{% endblock %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("nav_profile");
    d.className = "active";
 });
</script>
{% endblock javascript%}

templates/users/edit_profile.html
{% extends "base_portal.html" %}

{% block body %}

{% if profile_changed %}
<h3>Your profile has been updated successfully.</h3>
{% endif %}
{% if not is_multiple_user %}
    <div class="span3">
        <ul class="thumbnails">
            <li class="span3">
                <br>
                <br>
                <a href="#" class="thumbnail"> <img id="profile_pic"  src="{{photo_path}}"></a>
            </li>
        </ul>

        <center>
            <b><a href="{% url dashboard.views.change_profile_pic owner_name=user%}">Change Profile Picture</a></b>
        </center>
    </div>
    <div class="span5">
{% else %}    
    <div class="span5 offset3">
{% endif %}    
        <div id="main_edit_profile">
            <div id ="heading">
                <center>
                    <h3>{{department_name}}
                    {% if is_core %}
                    Core Details
                    {% else %}
                    Coordinator Details
                    {% endif %} </h3><br>
                </center>
            </div>

            <div>
                <form class="well" method="POST" id="profile_form" action="{% url users.views.handle_profile owner_name=user%}">
                    {% csrf_token %}
                    <table id="edit_details" cellspacing="12">
                        {{ profile_form }}

                    </table>
                    <input type="submit" value="Finish Editing" name="update"  >

                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("nav_profile");
    d.className = "active";
 });
</script>
<script type="text/javascript">  //initialise django-chosen
$("#id_hostel").chosen();
</script>
{% endblock javascript%}

templates/users/emailcoords.html
hey {{coordname}}
	you are invited to join erp .cool
	{{SITE_URL}}
	this is your activation key {{activationkey}}

templates/users/register.html
{% extends "home.html" %}

{% block title %}
{{ block.super }} 
{% endblock title %}

{% block body %}
<br />
<h1>
User Registration

</h1>
<p>
  Please fill in the following details: 
</p>
<form action="{{SITE_URL}}/users/register/{{dept_name}}/" method="POST">{% csrf_token %}
  <div class="register">
    <table name="register">
      {{ user_form }}
	<input type="hidden" value ="{{dept_name}}" name="dept_name" >
    </table>
    <hr />
    <input type="submit" value="Register" >
  </div>
</form>

note:for testing phase if you have not got invite your dept by default is Events
{% endblock %}

templates/users/view_profile.html
{% extends "base_portal.html" %}

{% block body %}


<div class="row">
    <div id="username" class="span3 offset3">
            <center><h2>{{ profile.name}} {% if profile.nickname %}({{ profile.nickname }}){% endif %}</h2></center>
<br/>
<br/>
    </div>
    <div class="row">
        <div class="span3 offset1">
            <ul class="thumbnails">
                <li class="span3">
                    <br>
                    <br>
                    <a href="#" class="thumbnail"> <img id="profile_pic" src="{{photo_path}}"> </a>
                </li>
            </ul>

        </div>
        <div class="span5">
            <center>
            {% if profile.department %}
                <h3>
                {{ dept }}
            {{ group }}</h3>

             {% for dept in  profile.department.all %}
                   {% if forloop.counter == 1 %}
                       {{ dept }}
                   {% else %}
                      /{{ dept }}
                   {% endif %}
             {% endfor %}
            {% else %} <!-- A multiple user -->
                {% if is_core %}
                    <h3> Events {{ group }}</h3> <!-- Assuming that the only multiple department core would be the Events core. -->
                {% else %}
                <h3>{{ group }}</h3> <!-- A multiple coord -->
                {% endif %}
            {% endif %}    
            </center>
            {% if is_core %}
            <center>
                <h6><a href="{% url tasks.views.display_portal owner_name=page_owner %}" class="button big" > Dashboard </a></h6>
            </center>
            {%endif%}
            <table class="table table-striped" id="details_table">

                <br/>

                <div id="complete_details">
                    <tr>
                        <td>
                        <div class ="left" >
                            Contact Number
                        </div></td>
                        <td>
                        <div class="right" >
                            {{profile.chennai_number}}
                        </div></td>
                    </tr>

                    <tr>
                        <td>
                        <div class ="left" >
                            Summer Contact
                        </div></td>
                        <td>
                        <div class="right" >
                            {{profile.summer_number}}
                        </div></td>
                    </tr>

                    <tr>
                        <td>
                        <div class ="left" >
                            Summer Stay
                        </div></td>
                        <td>
                        <div class="right" >
                            {{profile.summer_stay}}
                        </div></td>
                    </tr>

                    <tr>
                        <td>
                        <div class ="left" >
                            Hostel
                        </div></td>
                        <td>
                        <div class="right" >
                            {{profile.hostel}}
                        </div></td>
                    </tr>

                    <tr>
                        <td>
                        <div class ="left" >
                            Room number
                        </div></td>
                        <td>
                        <div class="right" >
                            {{profile.room_no}}
                        </div></td>
                    </tr>

                </div>
            </table>
            {% if not is_visitor %}
            <center>
                <a href="{% url users.views.handle_profile owner_name=user%}"  id ="edit_profile"> Edit profile </a>
            </center>
            {% endif %}
        </div>
{% endblock %}

{% block javascript %}
{{ block.super }}
{% if not is_visitor  %}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("nav_profile");
    d.className = "active";
 });
</script>
{% endif %}
{% endblock javascript%}
 