prizes/urls.py
from django.views.generic.simple import *
from django.contrib import admin
from django.conf.urls import *
from django.conf.urls.defaults import *

urlpatterns = patterns('erp.prizes.views', 
      (r'^pdf/$','event_participation_pdf'),
      (r'^pdf/(?P<event_id>\d{1,3})/$','event_participation_pdf'),
      (r'^assign_new/$','assign_barcode_new'),
      (r'^display/(?P<shaastra_id>\w+)/$','display_portal'), 
      (r'^upload/$', 'upload_file'),
      (r'^upload/(?P<event_name>\d{1,3})/$', 'upload_file'),
      (r'^eventdetails/$','fillEventDetails'),
      (r'^eventdetails/(?P<event_name>\d{1,3})/$','fillEventDetails'),      
      (r'^prize/$', 'choosePosition'),
      (r'^prize/(?P<event_name>\d{1,3})/$', 'choosePosition'),
      (r'^prize/(?P<event_name>\d{1,3})/position/$', 'prize_assign'),
      (r'^prize/(?P<event_name>\d{1,3})/position/(?P<position>\d{1,2})/$', 'prize_assign'),
      (r'^viewlist/$', 'viewFinal'),
      (r'^finalise/$', 'setFinal'),
      (r'^finalise/(?P<event_name>\d{1,3})/$', 'setFinal'),
      #(r'^cheque/$', 'cheque_assign'),
      #(r'^cheque/(?P<event_name>\d{1,3})/$', 'cheque_assign'),
      (r'^registerparticipants/$','registerparticipants'),
      (r'^registerparticipants/(?P<event_name>\d{1,3})/$','registerparticipants'),
      (r'^assign/$','assign_barcode'),  
)

urls.py
from django.conf.urls import *
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
from django.conf import settings
from erp.tasks.views import *
from erp.users.views import *
from erp.home.views import *
from erp.feedback.views import *
from erp.finance.views import *
import haystack
from haystack.views import SearchView
from haystack.forms import ModelSearchForm
from haystack.forms import SearchForm
from haystack.views import search_view_factory
from django.conf.urls import *
from tasks.views import *
from django.conf.urls.defaults import *

#haystack.autodiscover()
dajaxice_autodiscover()
#admin.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)
 
urlpatterns = patterns('',
    #(r'^134c036048b637ac75edcd4352212e55/$', 'erp.home.dbscript.write_into_db'), #used to load coord/core details into db.
    (r'^dajaxice/', include('dajaxice.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    (r'^forgot_password/$','erp.home.views.forgot_password'),
    #(r'^search/', include('haystack.urls')),
    url(r'^$', 'erp.home.views.login', name='home'),
    (r'^search/', include('erp.search.urls')),
    #(r'^erp/$', include('erp.home.urls')),
    (r'^erp/home/',include('erp.home.urls')),
    #(r'^erp/users/', include('erp.users.urls')),
    #(r'^erp/dashboard/',include('erp.dashboard.urls')),	
    # Make the above 2 URLConfs look like these 2 below
	(r'^erp/(?P<owner_name>\w+)/feedback/', include('erp.feedback.urls')),
	(r'^erp/feedback/', include('erp.feedback.urls')),
	(r'^erp/finance_portal/',include('erp.finance.urls')),
	(r'^erp/facilities/',include('erp.facilities.urls')),
	(r'^erp/prizes/(?P<owner_name>\w+)/', include('erp.prizes.urls')),
    (r'^erp/(?P<owner_name>\w+)/users/', include('erp.users.urls')),
    (r'^erp/(?P<owner_name>\w+)/dashboard/',include('erp.dashboard.urls')),	
    (r'^erp/(?P<owner_name>\w+)/', include('erp.tasks.urls')),
    (r'^erp/forgot_password/$', 'erp.home.views.forgot_password'),
    (r'^loaddata/$', 'erp.dashboard.views.load_data'), #used to load test data into db.
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    
    #(r'^now/sign.html$', sign_in, ),
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url(r'^task/remainder/email/$', 'erp.tasks.views.remainder', name='remainder'),
)

prizes/models.py
from django.db import models
from erp.department.models import Department
from django.contrib.auth.models import User

GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))

class Participant(models.Model):
    """
    The participant's data.
    """
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,
                              default='F')
    age = models.IntegerField(default=18)
    branch = models.CharField(max_length=50, blank=True, null=True,
                              help_text='Your branch of study')
    mobile_number = models.CharField(max_length=15, null=True,
            help_text='Please enter your current mobile number')
    college = models.CharField(max_length=100)
    college_roll = models.CharField(max_length=40, null=True)
    shaastra_id = models.CharField(max_length=30, blank=True)
    events = models.ManyToManyField(Department,
            related_name='participants', null=True)
    
    def __str__(self):
        return self.shaastra_id

class BarcodeMap(models.Model):
    """
    Maps barcode to participant
    """
    barcode = models.CharField(max_length=128,blank=True)
    shaastra_id = models.ForeignKey(Participant, blank=True, null=True)  
    
    def __str__(self):
        return self.barcode
        
class Prize(models.Model):
    """
    The winner's details and cheque nos
    """
    participant_1 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_1')
    participant_2 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_2')
    participant_3 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_3')
    participant_4 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_4')
    participant_5 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_5')
    participant_6 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_6')
    participant_7 = models.ForeignKey(Participant,blank=True, null=True, related_name = 'member_7')
    position = models.CharField(max_length=10,blank=True)
    event = models.ForeignKey(Department)
    details = models.CharField(max_length=250,blank=True)
    cheque = models.CharField(max_length=15,blank=True)
    # User who is uploading the entry
    user = models.ForeignKey(User)  
    
    def __str__(self):
        return self.participant_1.shaastra_id
        
class EventDetails(models.Model):
    event = models.ForeignKey(Department)
    team_nos = models.IntegerField()
    max_members = models.IntegerField()
    winner_nos = models.IntegerField(blank=True, null=True)
    finalist_nos = models.IntegerField(blank=True, null=True)
    certificate_nos = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.event.Dept_Name      

class College(models.Model):

    name = models.CharField(max_length=255,
                            help_text='The name of your college. Please refrain from using short forms.'
                            )
    city = models.CharField(max_length=30,
                            help_text='The name of the city where your college is located. Please refrain from using short forms.'
                            )
    state = models.CharField(max_length=40,help_text='The state where your college is located. Select from the drop down list'
                             )

    def __unicode__(self):
        return '%s, %s, %s' % (self.name, self.city, self.state)

    class Admin:
        pass

    class Meta:
        db_table='users_college'

class ParticipantUser(models.Model):
    user=models.ForeignKey(User)
    gender = models.CharField(max_length=1,
                              default='F')
    age = models.IntegerField(default=18)
    branch = models.CharField(max_length=50, blank=True, null=True,
                              help_text='Your branch of study')
    mobile_number = models.CharField(max_length=15, null=True,
            help_text='Please enter your current mobile number')
    college = models.ForeignKey(College, null=True, blank=True)
    college_roll = models.CharField(max_length=40, null=True)

    shaastra_id = models.CharField(max_length = 20, unique = True, null=True)

    activation_key = models.CharField(max_length=40, null=True)
    key_expires = models.DateTimeField(null=True)
    want_accomodation = models.BooleanField(default=False, help_text = "This doesn't guarantee accommodation during Shaastra.")
    is_core = models.BooleanField(default=False)
    is_hospi = models.BooleanField(default=False)
    facebook_id = models.CharField(max_length=20)
    access_token = models.CharField(max_length=250)

    class Admin:
        pass
        
    class Meta:
        db_table='users_userprofile'
        
class Team(models.Model):
    name = models.CharField(max_length = 250)
    events = models.ManyToManyField(Department, null=True)
                
    def __unicode__(self):
        return self.name

templates/prizes/cheque_table.html
{% extends "base_portal.html" %}

{% block tabs %}

<div class="tabbable span8">
    <div class="tab-content">
    <div class="row">
    <div class="span5">
         <div class="well span5 offset1">
      <center>  <h4>Assign Cheques to event winners!</h4> 
       <br/>
       
       Submitting a form will save all entries and a new form will load.<br> 
       <br /> Select the Shaastra ID of the participant and assign him a cheque.
       <u>Please submit as often as possible to save work.</u>
       <br/>
       </center>
       </div>
        <form action="" method="POST">
        {% csrf_token %}
        {{ winnerformset.management_form }}
        <table class="table table-striped table-bordered span5 offset1">
        <tr><th>S.No</th><th>Shaastra ID</th><th>Cheque No</th>
        {% for winnerform in winnerformset %}
            <tr><td>{{ forloop.counter }}.&emsp;</td>
            
          {% for field in winnerform.visible_fields %}
                   <td>{{ field }}</td>
                {% endfor %}
            </tr>
                {% for field in winnerform.hidden_fields %}
                    {{ field }}
                {% endfor %}
        {% endfor %}
        </table>
        <br/>
        <input type="submit" class="btn btn-primary" name="submit_continue" value="Submit and continue"/>
        </form>
    </div>
    </div>
    <div class="span3">
    <h4>Winners:</h4><br/><br/>
    <table class="table">
    <tr><th>S.No.</th><th>Name</th><th>Position</th><th>Cheque No</th><th>ShaastraID</th></tr>
    {% for winner in winnerList %}
    <tr><td>{{ forloop.counter }}.</td><td>{{ winner.participant.name }}</td><td>{{ winner.position }}</td><td>{{ winner.cheque }}</td><td>{{ winner.participant.shaastra_id }}</td></tr>
    {% endfor %}
    </table>
    </div> 
    </div><!-- /.tab-content -->
</div><!-- /.tabbable -->

{% endblock tabs %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_cheque_assign");
    var e = document.getElementById("li_cheque_assign_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
$('.chzn-select').chosen();
</script>
{% endblock javascript%}

templates/prizes/choose_position.html
{% extends "base_portal.html" %}

{% block tabs %}
{% if PPM %}
<center><h4>Choose finalist (Position No.):</h4></center><br/>
<table class="table">
{% for position in positions %}
<tr><td>
<a href="{% url prizes.views.prize_assign owner_name=user event_name=event_name position=position %}">{{ position }}</a>
</td></tr>
{% endfor %}
</table>
{% endif %}
<center><h4>Finalist Details:</h4>
Number of Places with Cash Prize and Cerificate (1st, 2nd, 3rd etc.): {{ eventdetails.winner_nos }}</center><br/>
<table class="table table-bordered">
<tr>
<th>Members</th>
<th>Position</th>
<th>Details</th>
<th>Cheque</th>
</tr>
{% for finalist in finalist_details %}
<tr>
<td>
<table class="table table-bordered">
<tr>
<th>Name</th>
<th>Shaastra ID</th>
<th>Barcode</th>
</tr>
{% if finalist.participant_1.shaastra_id %}
<tr>
<td>{{ finalist.participant_1.name }}</td><td>{{ finalist.participant_1.shaastra_id }}</td><td>{{ finalist.participant_1.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_2.shaastra_id %}
<tr>
<td>{{ finalist.participant_2.name }}</td><td>{{ finalist.participant_2.shaastra_id }}</td><td>{{ finalist.participant_2.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_3.shaastra_id %}
<tr>
<td>{{ finalist.participant_3.name }}</td><td>{{ finalist.participant_3.shaastra_id }}</td><td>{{ finalist.participant_3.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_4.shaastra_id %}
<tr>
<td>{{ finalist.participant_4.name }}</td><td>{{ finalist.participant_4.shaastra_id }}</td><td>{{ finalist.participant_4.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_5.shaastra_id %}
<tr>
<td>{{ finalist.participant_5.name }}</td><td>{{ finalist.participant_5.shaastra_id }}</td><td>{{ finalist.participant_5.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_6.shaastra_id %}
<tr>
<td>{{ finalist.participant_6.name }}</td><td>{{ finalist.participant_6.shaastra_id }}</td><td>{{ finalist.participant_6.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
{% if finalist.participant_7.shaastra_id %}
<tr>
<td>{{ finalist.participant_7.name }}</td><td>{{ finalist.participant_7.shaastra_id }}</td><td>{{ finalist.participant_7.barcodemap_set.all.0.barcode }}</td>
</tr>
{% endif %}
</table>
</td>
<td>{{ finalist.position }}</td>
<td>{{ finalist.details }}</td>
<td>{{ finalist.cheque }}</td>
</tr>
{% endfor %}
</table>
{% if PPM %}
<a href="{% url prizes.views.setFinal owner_name=request.user event_name=event_name %}">Set this list as the final list of participants</a> - This option makes the event green in the event details page, to inform others that this is the finalised list.
{% endif %}
{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
        var d = document.getElementById("li_prize_assign");
            var e = document.getElementById("li_prize_assign_icon");
                d.className = "active";
                    e.className = e.className + " icon-white";
                     });
 $('.chzn-select').chosen();
</script>
{% endblock javascript%}
{% endblock %}

templates/prizes/display_prize.html
{% extends "base_portal.html" %}
{% block tabs %}
{% if not not_exists %}
<table class="table table-striped">
{{form.as_table}}
</table>
{% else %}
Invalid ShaastraID
{%endif%}
{% endblock %}

templates/prizes/display_profile.html
{% extends "base_portal.html" %}

{% block tabs %}

{% if not not_exists %}
{% if detail_error %}
<div class="row">
<div class="well">
<h4><u><center> This is participant has one or more fields empty. After mapping the barcode, please check and ask him/her to update their details on the mainsite. </center></u></h3>
</div>
</div>
{% endif %}
{% if participantform %}
<h3>Please do <i><u><b>NOT</b></u></i> change anything in the below form. It is solely for confirmation purposes.<br></h4>
<div class="well">
<form action="" method="POST">
{% csrf_token %}
<table class="table">
{% for field in participantform.visible_fields %}
<tr><td>{{field.label}}</td>
<td>{{field}}</td></tr>
{%endfor%}
</table>
<input type="submit" class="btn btn-primary btn-large offset1" name="submit_continue" value="Confirm"/>
</form>
<a href="{% url erp.prizes.views.assign_barcode_new owner_name=user %}"> Go Back </a>
</center>
</div>
{% endif %}
{% endif %}

{% if saved %}
<span class="label label-success">Saved entry</span><br />
<br />{% endif %}



{% if not_exists %}
<span class="label label-important">Invalid ShaastraID/Barcode</span><br />
<br />{% endif %}
{% if not participantform %}
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" class="btn btn-primary btn-large offset1" name="submit_continue" value="Submit and continue"/>
</form>
{% endif %}
{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
        var d = document.getElementById("li_barcode_assign");
            var e = document.getElementById("li_barcode_assign_icon");
                d.className = "active";
                    e.className = e.className + " icon-white";
                     });
 $('.chzn-select').chosen();
</script>
<script>  
 var subjects = {{ idList|safe }}
$('.search').typeahead({source: subjects})  
</script>  
{% endblock javascript%}
{% endblock %}

templates/prizes/eventdetailschoices.html
{% extends "base_portal.html" %}

{% block tabs %}
<center><h4>{{ page_name }} - Choose Event</h4></center><br/>
The list of finalists have been decided for the events in <span style="color:#00FF00;">green</span>.
 You can also view the list of these events <a href="{% url prizes.views.viewFinal owner_name=user %}">here</a>.<br/><br/>
<style type="text/css">
      .complete {
      color: #00FF00;
      }      
</style>
<table class="table">
{% for classvalue, event in eventList %}
<tr><td>
<a href="{{ request.path }}{{ event.id }}/" class="{{ classvalue }}">{{event.Dept_Name}}</a>
</td></tr>
{% endfor %}
{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
        var d = document.getElementById("li_prize_assign");
            var e = document.getElementById("li_prize_assign_icon");
                d.className = "active";
                    e.className = e.className + " icon-white";
                     });
 $('.chzn-select').chosen();
</script>
{% endblock javascript%}
{% endblock %}

templates/prizes/hospiregistration.html
{% extends "base_portal.html" %}

{% block tabs %}

<div class="tabbable span8">
    <div class="tab-content">
    <div class="row">
    <div class="well span5 offset1">
      <center>  <h4>Assign barcodes to Shaastra Particpants.</h4> 
       <br/>
       Submitting a form will save all entries and a new form will load.<br> <u>Please submit as often as possible to save work.</u>
       <br/>
       </center>
       </div>
    <div class="span offset1">
        <form action="" method="POST">
        {% csrf_token %}
        {{ barcodeformset.management_form }}
        
        <table class="table-condensed table-striped">
            <tr><th>S.No</th><th> Barcode </th> <th> Paticipant Shaastra ID </th><th>Errors(If any)</th></tr>
            <tr>
            
            {% for barcodeform in barcodeformset %}
                <td>{{ forloop.counter }}.&emsp;</td>
                {% for field in barcodeform.visible_fields %}
                   <td>{{ field }}</td>
                   {% if field.errors %}
                   <td>{{field.errors}}</td>
                   {% endif %}
                {% endfor %}
            </tr>
            {%endfor%}

        </table>

        <table>    
           <tr>
                {% for field in barcodeform.hidden_fields %}
                <td> {{ field }} </td>
                {% endfor %}
           </tr>
        </table>
        <br/>
        <center><input type="submit" class="btn btn-primary btn-large offset1" name="submit_continue" value="Submit and continue"/>
        </center>
        </form>
    </div>
    
    </div>
    </div><!-- /.tab-content -->
</div><!-- /.tabbable -->

{% endblock tabs %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_barcode_assign");
    var e = document.getElementById("li_barcode_assign_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
$('.chzn-select').chosen();
</script>
{% endblock javascript%}

templates/prizes/prize_assign.html
{% extends "base_portal.html" %}

{% block title %}

{{ block.super }}
Department Portal | {{ po_dept_name }}
{% endblock title %}

{% block content-heading %}
<div class="content-heading">
    <h1>Portal - {{ po_dept_name }} Department </h1>
</div>
{% endblock content-heading %}

{% block tabs %}

<div class="tabbable span8">       
<div class="row">

    <div class="well">
    <center>    
        <form method="post" action="/">
            {% csrf_token %}
            ID<br>
            <input id="id" type="text" /> <br>
            Cheque No<br>
            <input id="serial" type="text" /><br>
            <button id ="submit" type="button" class = "btn btn-inverse" onclick="assign();">Submit</button>
        </form>
    </center>
    </div>

</div>
<br>    
<div class="row">
    <center>
    <div class="">
        <h5> To edit, simply re-enter the ID and cheque no.</h>
    </div>
    </center><br>
   <div id="assign_table">
       {% include "prizes/assign_table.html" %}
   </div>

</div>



{% endblock tabs %}
    
{% block javascript %}
{{ block.super }}

{% load dajaxice_templatetags %}
{% dajaxice_js_import %}	

<script type="text/javascript">
			function assign() {
			    id='#id'; serial='#serial';
			    id=$(id).val()
			    serial=$(serial).val()
			    Dajaxice.prizes.assign(Dajax.process,{
					'id' : id,
                    'serial' : serial,
   				});
			}

        </script>

<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_prize_assign");
    var e = document.getElementById("li_prize_assign_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
 $('.chzn-select').chosen();
</script>
{% endblock javascript%}

templates/prizes/prize_base.html
{% extends "base_portal.html" %}

{% block title %}

{{ block.super }}
Department Portal | {{ po_dept_name }}
{% endblock title %}

{% block content-heading %}
<div class="content-heading">
    <h1>Portal - {{ po_dept_name }} Department </h1>
</div>
{% endblock content-heading %}

{% block tabs %}

<div class="tabbable span8">       
<div class="row">

    <div class="well span3">
        <form method="post" action="/">
            {% csrf_token %}
            Name<br>
            <input id="name1" type="text" /> <br>
            Position<br>
            <input id="position1" type="text" /><br>
            Other details<br>
            <input id="details1" type="text" /><br>
            <button id ="submit" type="button" class = "btn btn-inverse" onclick="prize(id=1);">Submit</button>
        </form>
    </div>


    <div class="well span3">
        <form method="post" action="/">
            {% csrf_token %}
            Name<br>
            <input id="name2" type="text" /> <br>
            Position<br>
            <input id="position2" type="text" /><br>
            Other details<br>
            <input id="details2" type="text" /><br>
            <button id ="submit" type="button" class = "btn btn-inverse" onclick="prize(id=2);">Submit</button>
        </form>
    </div>
</div>
<br>    
<div class="row">
    <div class="well">
        <h6> NOTE: If the details appear in the table below, please do not submit the details again. They have been saved. </h6>
        <h5> You can submit entries simultaneously without affecting each other </h5>
    </div>

   <div id="prize_table">
       {% include "prizes/prize_table.html" %}
   </div>

</div>



{% endblock tabs %}
    
{% block javascript %}
{{ block.super }}

{% load dajaxice_templatetags %}
{% dajaxice_js_import %}	

<script type="text/javascript">
			function prize(id) {
			    name='#name'+id; position='#position'+id; details='#details'+id;
			    name=$(name).val()
			    position=$(position).val()
			    details=$(details).val()
				Dajaxice.prizes.submit(Dajax.process,{
					'name' : name,
                    'position' : position,
                    'details' : details,
   				});
			}

        </script>

<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_prize");
    var e = document.getElementById("li_prize_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
</script>
{% endblock javascript%}

templates/prizes/prize_event.html
{% extends "base_portal.html" %}

{% block tabs %}

<table class="table">
{% for event in events %}
<tr><td>
<a href={% url prizes.views.prize_assign owner_name=user event_name=event.id %}>{{event.Dept_Name}}</a><br />
</tr></td>
{% endfor %}
{% endblock %}

templates/prizes/registerparticipants.html
{% extends "base_portal.html" %}

{% block tabs %}

<div class="tabbable span8">
    <div class="tab-content">
    <div class="row">
    <div class="span5">
    <div class="well">
        <center><h4>Event Registration</h4>
        Scan the barcodes (or choose the Shaastra ID) of participants registering for the event <b>"{{ eventname }}"</b>. Entering both may cause conflicts.<br/>
       <u>Please submit as often as possible to save work.</u></center>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="span5">
        {% if error %}
            <div class="alert alert-error fade in">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                Incorrect data entered - <b>{{ error }}</b><br/>Please enter the correct barcode, or enter the correct Shaastra ID instead.
            </div>
        {% endif %}
        <form action="" method="POST">
        {% csrf_token %}
        {{ barcodemapformset.management_form }}
        <table>
        {% for barcodemapform in barcodemapformset %}
            <tr><td>{{ forloop.counter }}.</td></tr>
            {{ barcodemapform.non_field_errors }}
            {{ barcodemapform.as_table }}
        {% endfor %}
        </table>
        <br/>
        <input id="formset_submit" type="submit" class="btn btn-primary" name="submit_continue" value="Submit and continue"/>
        </form>
    </div>
    <div class="span3">
    <form action="{% url prizes.views.upload_file owner_name=user event_name=event_name %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ uploadform.non_field_errors }}</p>
            <p>{{ uploadform.docfile.label_tag }} {{ uploadform.docfile.help_text }}</p>
            <p>
                {{ uploadform.docfile.errors }}
                {{ uploadform.docfile }}
            </p>
            <p><input type="submit" class="btn btn-primary" value="Upload" /></p>
        </form>
    </div>
    <div class="span3">
    <h4>Registered Participants:</h4><br/>
    <table class="table">
    {% if participantList %}
    <br/>
    <tr><th>S.No.</th><th>Name</th><th>Shaastra ID</th><th>Barcode</th></tr>
    {% for participant in participantList %}
    <tr><td>{{ forloop.counter }}.</td><td>{{ participant.name }}</td><td>{{ participant.shaastra_id }}</td><td>{{ participant.barcodemap_set.all.0.barcode }}</td></tr>
    {% endfor %}
    </table>
    {% else %}
    No participants registered.
    {% endif %}
    </div>    
    </div>
    </div><!-- /.tab-content -->
</div><!-- /.tabbable -->

{% endblock tabs %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_eventregn");
    var e = document.getElementById("li_eventregn_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
$('.chzn-select').chosen();
</script>
<script>  
 var subjects = {{ idList|safe }}
$('.search').typeahead({source: subjects})  
</script>  
{% endblock javascript%}