tasks/urls.py
from django.views.generic.simple import *
from django.contrib import admin
from django.conf.urls import *
from django.conf.urls.defaults import *

# TODO
# Caution : Any non-matched url goes straight to display_portal and
# gives an error since a user of that name would not be found.
urlpatterns = patterns('erp.tasks.views',
      (r'^$', 'display_portal'),
      #(r'^search/', include('haystack.urls')),

      (r'^create', 'edit_task'),
      (r'^login/(?P<department>[^/]+)/$', 'multiple_login'),
      (r'^logout/$','multiple_logout'),
      (r'^task/(?P<task_id>[0-9]+)', 'edit_task'),
      (r'^display_task/(?P<task_id>[0-9]+)?', 'display_task'),
      (r'^subtask/(?P<subtask_id>[0-9]+)', 'edit_subtask'),
      (r'^display_subtask/(?P<subtask_id>[0-9]+)?', 'display_subtask'),
      (r'^department/(?P<department_name>$\w+)?$', 'display_department_portal'),
      # (r'^(\w+)?$', 'display_portal'),
)

urlpatterns +=patterns('erp.tasks.pdfMakeViews',
      (r'^report/$', 'ReportGen'),
)

urls.py
from django.conf.urls import *
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
from django.conf import settings
from erp.tasks.views import *
from erp.users.views import *
from erp.home.views import *
from erp.feedback.views import *
from erp.finance.views import *
import haystack
from haystack.views import SearchView
from haystack.forms import ModelSearchForm
from haystack.forms import SearchForm
from haystack.views import search_view_factory
from django.conf.urls import *
from tasks.views import *
from django.conf.urls.defaults import *

#haystack.autodiscover()
dajaxice_autodiscover()
#admin.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)
 
urlpatterns = patterns('',
    #(r'^134c036048b637ac75edcd4352212e55/$', 'erp.home.dbscript.write_into_db'), #used to load coord/core details into db.
    (r'^dajaxice/', include('dajaxice.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    (r'^forgot_password/$','erp.home.views.forgot_password'),
    #(r'^search/', include('haystack.urls')),
    url(r'^$', 'erp.home.views.login', name='home'),
    (r'^search/', include('erp.search.urls')),
    #(r'^erp/$', include('erp.home.urls')),
    (r'^erp/home/',include('erp.home.urls')),
    #(r'^erp/users/', include('erp.users.urls')),
    #(r'^erp/dashboard/',include('erp.dashboard.urls')),	
    # Make the above 2 URLConfs look like these 2 below
	(r'^erp/(?P<owner_name>\w+)/feedback/', include('erp.feedback.urls')),
	(r'^erp/feedback/', include('erp.feedback.urls')),
	(r'^erp/finance_portal/',include('erp.finance.urls')),
	(r'^erp/facilities/',include('erp.facilities.urls')),
	(r'^erp/prizes/(?P<owner_name>\w+)/', include('erp.prizes.urls')),
    (r'^erp/(?P<owner_name>\w+)/users/', include('erp.users.urls')),
    (r'^erp/(?P<owner_name>\w+)/dashboard/',include('erp.dashboard.urls')),	
    (r'^erp/(?P<owner_name>\w+)/', include('erp.tasks.urls')),
    (r'^erp/forgot_password/$', 'erp.home.views.forgot_password'),
    (r'^loaddata/$', 'erp.dashboard.views.load_data'), #used to load test data into db.
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    
    #(r'^now/sign.html$', sign_in, ),
    # Examples:
    # url(r'^$', 'erp.views.home', name='home'),
    # url(r'^erp/', include('erp.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url(r'^task/remainder/email/$', 'erp.tasks.views.remainder', name='remainder'),
)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from erp.department.models import Department
from erp.misc.helper import is_core, is_coord, get_page_owner

# Create your models here.
#The choices may be cup level but if any thing better pls do change.
STAT_CHOICES= (
	('O','Open'),
	('C','Completed'),
	('L','Overdue'),
	('N','Almost'),
)

DEFAULT_STATUS = 'O'
    
class AbstractBaseTask(models.Model):
    """
    Abstract Base Class for Task, SubTask.

    TODO:
    * File upload
    * Draft saving
    * QMS Manager for the Task
    """
    subject         = models.CharField(max_length=100 , null=True)
    description     = models.TextField(null=True , blank=True)
    creator         = models.ForeignKey(User, related_name = '%(app_label)s_%(class)s_creator')
    creation_date   = models.DateTimeField (auto_now = True, editable = False)
    deadline        = models.DateField(null=True , blank=True)
    status          = models.CharField(max_length=1,choices=STAT_CHOICES,default = DEFAULT_STATUS)	
    completion_date = models.DateField(null=True , blank=True)
    feedback        = models.TextField(null=True, blank=True)
    class Meta:
        abstract = True
        
class Task(AbstractBaseTask):

    """
    Task Model

    Note : The department where the Task originated is understood from
    the Creator's department. As of now, only Cores can create Tasks.

    A Task mainly consists of SubTasks which are created and assigned by the respective Cores of each department.
    """

    def is_owner (self, user):
        """
        user is the owner of the current Task if
        - user is a Core in the Task's department
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.creator.get_profile ().department
        return user.get_profile ().department == self.creator.get_profile ().department and (not is_coord (user))

    def __str__(self):
        return self.subject

    class Admin:
        pass

class SubTask(AbstractBaseTask):
    """
    SubTask Model

    As of now, SubTasks can be created mainly in two places :

    * When a Core breaks Tasks down into SubTasks and assigns some of
      them to Coords in his own department and/or delegates a SubTask
      to another Department (whose core has to then assign that
      SubTask to that department's coords, possibly creating more
      SubTasks as required)

    * When a Coord creates goals with deadlines for himself (these are
      called SubTasks but will actually be shown in his Timeline and
      handled differently from SubTasks that have been assigned to him
      by Cores)
    """
    coords = models.ManyToManyField (User, blank = True)
    department = models.ForeignKey (Department)
    task = models.ForeignKey (Task)

    def is_owner (self, user):
        """
        user is the owner of the current SubTask if
        - user is a Core in the department which created the Task
          which SubTask is related to
        - user is a Core in the department to which SubTask is assigned
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.task.creator.get_profile ().department
        print 'SubTask Dept : ', self.department
        user_dept = user.get_profile().department
        return (not is_coord (user)) and (
            (user_dept == self.task.creator.get_profile ().department) or
            (user_dept == self.department))

    def is_assignee (self, user):
        """
        Return True if user is a Coord who has been assigned this subtask.
        """
        print 'User Dept : ', user.get_profile ().department
        print 'Is Coord : ', is_coord (user)
        user_dept = user.get_profile().department
        return is_coord (user) and (self.coords.filter (id = user.id).exists ())

    def __str__(self):
        return self.subject

    class Admin:
        pass

class AbstractComment (models.Model):
    """
    Abstract Base Class to store a comment.

    Timestamp helps to order comments. It is generated automatically.
    Author can be used to select particular comments based on the author.
    """
    author = models.ForeignKey (User, related_name = '%(app_label)s_%(class)s_author')
    comment_string = models.TextField ()
    time_stamp = models.DateTimeField (auto_now = True, editable = False)

    class Meta:
        abstract = True
        ordering = ['time_stamp']

class TaskComment(AbstractComment):
    """
    Comment written for a Task.
    """
    task = models.ForeignKey (Task)

    def __str__(self):
        return '%s %s' %(self.task.subject, self.id)
    class Admin:
        pass
        
        
class SubTaskComment(AbstractComment):
    """
    Comment written for a SubTask
    """
    subtask = models.ForeignKey (SubTask)

    def __str__(self):
        return '%s %s' %(self.subtask.subject, self.id)
    class Admin:
        pass
        
class Label(models.Model):
    labelname = models.ForeignKey(Task, related_name="task_label")
    
class Update (AbstractComment):
    """
    Used by Coord to send updates to a Core
    """
    class Admin:
        pass

tasks/forms.py
from django.db import models
from django.forms import ModelForm
from models import *
from django import forms
from chosen import forms as chosenforms
from erp.department.models import *
from erp.users.models import *
from django.contrib.auth.models import User
#from chosen import widgets as chosenwidgets

class TaskCommentForm (ModelForm):
	comment_string=forms.CharField(label='Comments',widget=forms.Textarea)
	class Meta:
		model=TaskComment
		exclude=('author','task')	

class SubTaskCommentForm (ModelForm):
    class Meta:
        model = SubTaskComment
        exclude = ('author', 'subtask')                

class UpdateForm (ModelForm):
    class Meta:
        model = Update
        exclude = ('author')

class TaskForm (ModelForm):
    class Meta:
        model = Task
        exclude = ('creator', 'completion_date')
        widgets = {'status': chosenforms.widgets.ChosenSelect()}

class SubTaskForm (ModelForm):
    class Meta:
        model = SubTask
        exclude = ['creator', 'task', 'completion_date']
        widgets = {'department':chosenforms.widgets.ChosenSelect(),'coords': chosenforms.widgets.ChosenSelectMultiple(),'status': chosenforms.widgets.ChosenSelect()}

#to restrict coords for a core. Currently all coords display for a core. Code results in cups because of a cup in
#      # Let the Core save the SubTask
#            curr_subtask_form = SubTaskForm (request.POST, instance = curr_subtask)  line 336 in tasks/views.py  
#
#

#   The Curry issue has been fixed. However, when trying to edit a form, it does not change the form because it isn't valid 
#   for some reason. Line 469  if curr_subtask_form.is_valid (): returns FALSE. So the subtask just reloads itself without any changes.
#

    def __init__(self, editor=None, *args, **kwargs):
        if isinstance(editor,User):
            # The reason it is isinstance is because when i'm editing a subtask in particular, 
            # junk values are getting passed to editor in POST method.
            # To check, make it
        # if editor:
            # The code will fail but editor will be a random dictionary of variables.
            super(SubTaskForm, self).__init__(*args, **kwargs)
            print "THIS IS", editor
            self.fields['coords'].queryset = User.objects.filter(userprofile__department=editor.get_profile().department)
            self.fields['coords'].label_from_instance = lambda obj: "%s - %s" % (obj.get_profile ().name, obj.get_profile ().nickname)
            self.fields['coords'].help_text = ''
        else:
            super(SubTaskForm, self).__init__(editor,*args, **kwargs)   

        
#hack if these fields need to be formatted        
#    def __init__(self, *args, **kwargs):
#        super(SubTaskForm, self).__init__(*args, **kwargs)
#        self.fields['subject'].widget.attrs['rows'] = '500'
#        self.fields['subject'].widget.attrs['cols'] = '500'
        

templates/tasks/comments.html
{% comment %}
{% if is_task_comment %}
<h2>Task - {{ curr_object.subject }}</h2>
{% else %}
<h2>Subtask - {{ curr_object.subject }}</h2>
{% endif %}
{% endcomment %}

{# Display existing comments #}

{% if comments %}
<br />
<h3>Comments</h3>
<table class="table table-bordered" >
  <tr>
    <th>Author</th>
    <th>Comment</th>
    <th>Time</th>
  </tr>
  {% for comment in comments %}
  <tr>
    <td><a href="{% url users.views.view_profile owner_name=comment.author.username %}">{{ comment.author.get_profile.name }}</a></td>
    <td>{{ comment.comment_string }}</td>
    <td>{{ comment.time_stamp }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
There are no Comments yet.
{% endif %}

<div id="comments_table">
    {% include "tasks/comment_table.html" %}
</div>
{# Comment Form #}

{% load dajaxice_templatetags %}
{% dajaxice_js_import %}
<script type="text/javascript">

    function comment(){
        var comment = $('#comments_field').val()
        if (comment=='')
        {
            $("#comments_alert").show()
            exit
        }
        $('#comments_field').val('')
        Dajaxice.tasks.comment(Dajax.process, {
                    'object_url' : document.URL,
                    'comment' : comment
                });
    }
      
</script>

<h2>Add a comment</h2>
<textarea class='comment' id="comments_field" placeholder="enter comment"></textarea>
<div>
<button class="btn btn-primary" type = "button" onclick="comment()" id="comment_button">Comment</button>
</div>
            <div class="alert alert-error span2 offset1 hide" id="comments_alert">
                <center>
                    <strong> Your comment is blank! </strong>
                </center>
            </div>
 

templates/tasks/department_portal.html
{% extends "base_portal.html" %}

{% block title %}
{{ block.super }}
Department Portal | {{ po_dept_name }}
{% endblock title %}

{% block content-heading %}
<div class="content-heading">
    <h1>Portal - {{ po_dept_name }} Department </h1>
</div>
{% endblock content-heading %}

{% block tabs %}

<div class="tabbable span8">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tabs1" data-toggle="tab"><i class="icon-tasks"></i> Timeline</a>
        </li>
        <li>
            <a href="#tabs2" data-toggle="tab"><i class="icon-refresh"></i> Updates</a>
        </li>
        <li>
            <a href="#tabs3" data-toggle="tab"><i class="icon-comment"></i> Shout!</a>
        </li>
    </ul>
    <div class="tab-content" style = "overflow: visible;">
        <div class="tab-pane active" id="tabs1">

            {% include "tasks/timeline.html" %}
        </div>
        <div class="tab-pane" id="tabs2">
            <h2>Updates</h2>
            {% include "tasks/display_updates.html" %}
        </div>
        <div class="tab-pane" id="tabs3" style="overflow:hidden;">
            {% include "tasks/shout.html" %}
        </div>
    </div>

{% endblock tabs %}
    
{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    var d = document.getElementById("li_department");
    var e = document.getElementById("li_department_icon");
    d.className = "active";
    e.className = e.className + " icon-white";
 });
</script>
{% endblock javascript%}

templates/tasks/display_task.html
{% extends "base_portal.html" %}

{% block title %}
{{ block.super }} 
Task
{% endblock title %}

{% block display_stuff %}

<!--include for comments -->
<script type="text/javascript" src="{{ MEDIA_URL }}js/comments.js"></script>
{% load dajaxice_templatetags %}
{% dajaxice_js_import %}
<!--include for comments -->

<center><h1>Task
{% if not is_coord %}
<a class="btn btn-primary btn-large pull-right" href="{% url erp.tasks.views.edit_task task_id=curr_task.id owner_name=page_owner %}">Edit Task &raquo;</a>
{% endif %}
</h1></center><br/>

<table class="table table-striped table-bordered">
  <tr>
    <th>Subject</th>
    <td> {{ curr_task.subject }} </td>
  </tr>
  <tr>
    <th>Description</th>
    <td> {{ curr_task.description }} </td>
  </tr>
  <tr>
    <th>Proposer</th>
    <td>
        <a href="{% url users.views.view_profile owner_name=curr_task.creator.username %}">{{ curr_task.creator.get_profile.name }}</a>
    </td>
  </tr>
  <tr>
    <th>Creation Date</th>
    <td> {{ curr_task.creation_date }} </td>
  </tr>
  <tr>
    <th>Deadline</th>
    <td> {{ curr_task.deadline }} </td>
  </tr>
  <tr>
    <th>Completion Date</th>
    {% if curr_task.completion_date %}
    <td> {{ curr_task.completion_date }} </td>
    {% else %}
    <td> Incomplete </td>
    {% endif %}
  </tr>
  <tr>
    <th>Status</th>
	{% if curr_task.status == "O" %}
		<td><span class="label label-warning">Open</span></td>
	{% endif %}
	{% if curr_task.status == "C" %}
		<td><span class="label label-success">Completed</span></td>	
	{% endif %}
	{% if curr_task.status == "L" %}
		<td><span class="label label-important">Overdue</span></td>
	{% endif %}
	{% if curr_task.status == "N" %}
		<td><span class="label label-info">Almost</span></td>
	{% endif %}

  </tr>
</table>

{% include "tasks/task_comments.html" %}

{% for curr_subtask in curr_task.subtask_set.all %}
<br />
<center><h2>SubTask {{ forloop.counter }} </h2></center>
{% with curr_subtask.subtaskcomment_set.all as comments %}
{% include "tasks/subtask_template.html" %}
{% endwith %}
{% endfor %}

{% endblock display_stuff %}

templates/tasks/multiple.html
{% extends "base_portal.html" %}

{% block title %}
{{ block.super }}
{% endblock title %}
{% block tabs %}
<h4> Which event would you like to manage?</h4>
<ul class="nav nav-pills">
{% for dept in depts %}
<li>
<a href="{% url tasks.views.multiple_login owner_name=page_owner department=dept %}">
<button class="btn btn-inverse">{{dept}}</button>
</a>
</li>
{% endfor %}                
</ul>

<h5>Thank you for spending time on Shaastra today.</h5>
{% endblock tabs %}

templates/tasks/shout.html
<style type="text/css">
	#shoutbox {
		position: relative;
		top: 10px;
		overflow: auto;
		height: 350px;
	}
	#shoutbox_heading {
		position: relative;
		font-family: Arial;
		font-size: 28px;
	}
	#add_shoutbox {
		position: relative;
	}

	#comment {
		font-weight: 300;
		font-size: 88%
	}

	#id_comments {
		height: 30px;
		width: 350px;
	}
</style>
{# load dajaxice_templatetags #}
    {# dajaxice_js_import #}
    <script src="/dajaxice/dajaxice.core.js" type="text/javascript" charset="utf-8"></script>

<div class="row">
    <div id="shoutbox" class="well span6">
        <!--We have to reload this area-->

        {% include "tasks/shoutbox.html" %}
        <!--We have to reload this area-->
    </div>
</div>
<div class="row">
    <div id="add_shoutbox" class="span6">
        <script type="text/javascript">
			function shout() {
				shout_text = $("#id_comments").val()
				if (shout_text == '') {
					$(".alert").show();
					exit
				}
				$("#shout_button").html('Shouting...')
				$("#id_comments").val('')
				Dajaxice.tasks.shout(Dajax.process, {
					'shout' : shout_text
				});
			}

        </script>

        {% if not is_visitor %}
        <center>
            <textarea id="id_comments" rows="10" cols="40" name="comments"></textarea>
            <button id ="shout_button" class = "btn btn-inverse btn-large" onclick="shout();">
                Shout!
            </button>
        </center>

        <center>
            <div class="alert alert-error span2 offset1 hide">
                <center>
                    <strong> Your shout is blank! </strong>
                </center>
            </div>
        </center>
     

        </form>
        {% endif %}
    </div>
</div>

templates/tasks/shoutbox.html
<div id="markup">
        {% for field in shouts %}
            <span id="nickname" ><a href="{% url users.views.view_profile owner_name=field.user%}"><strong>{{field.user.get_profile.name}}</strong></a>:</span> &nbsp;&nbsp;
            <span id="comment" >{{field.comments}}</span>
            <br/>
        {% endfor %}
</div>        

templates/tasks/subtask_comments.html
<div id="comments_table">
    {% include "tasks/comments/subtask_comment_table.html" %}
</div>
{# Comment Form #}
<h2>Add a comment</h2>
<textarea class='comment' id="comments_field_subtask_{{ curr_subtask.id }}" placeholder="enter comment">   
</textarea>

<div>
<button class="btn btn-primary" type="button" onclick="comment({{curr_subtask.id}}, 'False')" id="comment_button">Comment</button>
</div>
            <div class="alert alert-error span2 offset1 hide" id="comments_alert_subtask_{{curr_subtask.id}}">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <center>
                    <strong> Your comment is blank! </strong>
                </center>
            </div>
  

templates/tasks/task_comments.html
<div id="comments_table">
    {% include "tasks/comments/task_comment_table.html" %}
</div>
{# Comment Form #}

<h2>Add a comment</h2>
<textarea class='comment' id="comments_field_task_{{curr_task.id}}" placeholder="enter comment"></textarea>
<div>
<button class="btn btn-primary" onclick="comment({{curr_task.id}}, 'True')" id="comment_button">Comment</button>
</div>
            <div class="alert alert-error span2 offset1 hide" id="comments_alert_task_{{curr_task.id}}">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <center>
                    <strong> Your comment is blank! </strong>
                </center>
            </div>
  

templates/tasks/timeline.html
<h2>Timeline for {{ po_dept_name }} Department</h2>

{% if tasks_deleted %}
<div class="alert fade in">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    The selected tasks have been deleted.
</div>
{% endif %}

{% if not po_is_coord %}
<form action="" method="post">
{% csrf_token %}
{% endif %}

<div id="alertdiv">
</div>
<p>List of all Tasks in your Department</p>

{% if all_Tasks %}

<table class="table table-striped table-bordered span7">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Subtasks</th>
    <th>Creator</th>
    <th>Deadline</th>
    <th>Status</th>
    {% if not po_is_coord %}
    <th>Comments</th>
    <th>Delete</th>
    {% endif %}
  </tr>
  </thead>
  <tbody>
  {% for task in all_Tasks %}
  <tr>
    <td>
      <a href="{% url tasks.views.display_task task_id=task.id owner_name=page_owner %}">{{ task.subject }}</a>
    </td>
    <td>
    {% if task.subtask_set.all %}
        <div class="accordion" id="timeline_subtask_{{ task.id }}_accordion">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" href="#timeline_subtask_{{ task.id }}" data-parent="timeline_subtask_{{ task.id }}_accordion" data-toggle="collapse" onclick=showSubtasks("timeline","{{task.id}}");>
                        <i class="icon-plus-sign" id="timeline_subtask_{{ task.id }}_icon" style="margin-top:1px;"></i> <span id="timeline_subtask_{{ task.id }}_text">Show</span>
                    </a>
                </div>
                <div id="timeline_subtask_{{ task.id }}" class="accordion-body collapse" style="margin-left:20px;">
                {% for subtask in task.subtask_set.all %}
                <ul>
                <li><a href="{% url tasks.views.edit_subtask subtask_id=subtask.id owner_name=page_owner %}">{{ subtask.subject }}</a></li>
                </ul>    
                {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no subtasks present.</p>
    {% endif %}
    </td>
    <td>
        <a href="{% url users.views.view_profile owner_name=task.creator.username %}">{{ task.creator.get_profile.name }}</a>
    </td>
    <td> {{ task.deadline }} </td>
	{% if task.status == "O" %}
	<td><span class="label label-warning">Open</span></td>
	{% endif %}
	{% if task.status == "C" %}
	<td><span class="label label-success">Completed</span></td>
	{% endif %}
	{% if task.status == "L" %}
	<td><span class="label label-important">Overdue</span></td>
	{% endif %}
	{% if task.status == "N" %}
	<td><span class="label label-info">Almost</span></td>
	{% endif %}

    {% if not po_is_coord %}
    
        <td>
        {% if task.taskcomment_set.all %}
        <div class="accordion" id="timeline_comments_{{ task.id }}_accordion">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" href="#timeline_comments_{{ task.id }}" data-parent="timeline_comments_{{ task.id }}_accordion" data-toggle="collapse" onclick=showComments("timeline","{{task.id}}");>
                        <i class="icon-plus-sign" id="timeline_comments_{{ task.id }}_icon" style="margin-top:1px;"></i> <span id="timeline_comments_{{ task.id }}_text">Show</span>
                    </a>
                </div>
                <div id="timeline_comments_{{ task.id }}" class="accordion-body collapse">
                {% for comment in task.taskcomment_set.all %}
                <ul>
                <li>"{{ comment.comment_string }}"<br/>- <a href="{% url users.views.view_profile owner_name=comment.author.username %}">{{ comment.author.get_profile.name }}</a></li>
                </ul>    
                {% endfor %}
                </div>
            </div>
        </div>
        {% else %}
            <p>There are no comments present.</p>
        {% endif %}
        </td>
        
        <td>
        <input type="checkbox" name="delete_tasks" value="{{ task.id }}"/> 
        </td>
            
    {% endif %}

  </tr>
  {% endfor %}
  </tbody>
</table>
<br/>
<br/>
<a class="btn btn-info btn-large" href="{% url tasks.pdfMakeViews.ReportGen owner_name=page_owner %}" >Create PDF Report</a>

{% if not po_is_coord %}
<input class="btn btn-inverse btn-large pull-right" id="task_delete" type="button" value="Delete Selected Tasks"/>
</form>
{% endif %}

{% else %}
<h4>No Tasks have been set in your Department yet.</h4>
{% endif %}

templates/tasks/updates.html
{% if not po_is_core %}

{% if update_status == 'Success' %}
<h3> The message has been sent to the core </h3>
{% endif %}

{% if update_status == 'Failed' %}
<h2> We are unable to process your request. </h2>
{% endif %}

{% if update_status == 'Blank' %}
<!-- Enter something if required -->
{% endif %}

{% endif %}

{% if not po_is_coord %}
<h2>Updates in {{ po_dept_name }}  Department</h2>
{% else %}
{% if po_is_coord and is_visitor %}
<h2>{{ po_name }}'s previous Updates </h2>
{% else %}
<h2>Your Previous Updates</h2>
{% endif %}
{% endif %}

{% include "tasks/display_updates.html" %}

{% if not po_is_core and not is_visitor %}
<h2>Send an Update to the Core{% if po_is_coord %} and Supercoords{% endif %}</h2>
  <form action="" method="post">
  {% csrf_token %}
  {{ update_form.non_field_errors }}
  {{ update_form.comment_string.errors }}
  <label for="id_comment_string">Update:</label>
    {{ update_form.comment_string }}
  <input type = "submit" class="btn btn-primary btn-large" value="Submit">
  </form>
</div>
{% endif %}